import type { CategoryDefinition, ToolCategory, ToolDefinition } from './types';

export const categories: CategoryDefinition[] = [
  {
    id: 'calculator',
    name: 'Calculators',
    description: 'Reliable date, health, math, and finance calculations.',
    icon: 'Calculator',
  },
  { id: 'pdf', name: 'PDF', description: 'Organize, convert, and prepare documents.', icon: 'FileText' },
  { id: 'image', name: 'Images', description: 'Resize, convert, extract, and enhance images.', icon: 'Image' },
  { id: 'video', name: 'Video', description: 'Convert and optimize video for any destination.', icon: 'Clapperboard' },
  { id: 'audio', name: 'Audio', description: 'Convert, trim, and prepare sound files.', icon: 'AudioLines' },
  {
    id: 'business',
    name: 'Business',
    description: 'Create practical assets for daily work.',
    icon: 'BriefcaseBusiness',
  },
  { id: 'developer', name: 'Developer', description: 'Inspect, format, and generate developer data.', icon: 'Braces' },
  { id: 'ai', name: 'AI', description: 'Focused assistants for creative and knowledge work.', icon: 'Sparkles' },
  {
    id: 'web',
    name: 'Web / Development',
    description: 'Build, test, and ship better web experiences.',
    icon: 'CodeXml',
  },
];

const commonFaq = (name: string, browser = false) => [
  {
    question: `How does ${name} work?`,
    answer: browser
      ? 'This tool runs in your browser. Follow the workspace prompts to complete the task.'
      : 'The interface is ready, but the processing engine is not connected yet. No output is fabricated.',
  },
  {
    question: 'Do I need an account?',
    answer: 'No account is required for the basic browser tools currently available.',
  },
  {
    question: 'What happens to my files?',
    answer: browser
      ? 'Files used by this tool stay in your browser for the current session.'
      : 'Files are not uploaded or processed while this preview engine is unavailable.',
  },
];

export const tools: ToolDefinition[] = [
  ...[
    [
      'age-calculator',
      'Age Calculator',
      'Calculate an exact age and the time until the next birthday.',
      'CalendarDays',
      ['age', 'birthday calculator', 'date of birth calculator', 'how old am I'],
    ],
    [
      'date-calculator',
      'Date Calculator',
      'Add or subtract calendar years, months, weeks, and days.',
      'CalendarPlus',
      ['date', 'add days', 'subtract date', 'calendar'],
    ],
    [
      'date-difference-calculator',
      'Date Difference Calculator',
      'Find the exact calendar difference between two dates.',
      'CalendarRange',
      ['date difference', 'days between dates', 'duration'],
    ],
    [
      'time-calculator',
      'Time Calculator',
      'Add, subtract, or compare durations beyond 24 hours.',
      'Clock3',
      ['time', 'duration', 'hours minutes seconds'],
    ],
    [
      'bmi-calculator',
      'BMI Calculator',
      'Estimate adult body mass index using metric or imperial units.',
      'Activity',
      ['bmi', 'body mass index', 'healthy weight'],
    ],
    [
      'percentage-calculator',
      'Percentage Calculator',
      'Solve common percentage, change, and adjustment questions.',
      'Percent',
      ['percentage', 'percent change', 'increase', 'decrease'],
    ],
    [
      'compound-interest-calculator',
      'Compound Interest Calculator',
      'Estimate compound growth with optional recurring contributions.',
      'TrendingUp',
      ['compound interest', 'interest calculator', 'investment growth'],
    ],
    [
      'simple-interest-calculator',
      'Simple Interest Calculator',
      'Calculate simple interest for a principal, rate, and duration.',
      'BadgePercent',
      ['simple interest', 'principal', 'interest'],
    ],
    [
      'loan-calculator',
      'Loan Calculator',
      'Estimate payments and total interest for an amortizing loan.',
      'Landmark',
      ['loan payment', 'monthly payment', 'loan interest'],
    ],
    [
      'emi-calculator',
      'EMI Calculator',
      'Estimate an equated monthly instalment and total payable.',
      'ReceiptText',
      ['emi', 'monthly installment', 'loan emi', 'emi calculator'],
    ],
    [
      'mortgage-calculator',
      'Mortgage Calculator',
      'Estimate a home loan payment with optional ownership costs.',
      'House',
      ['home loan', 'mortgage payment', 'house loan'],
    ],
    [
      'investment-calculator',
      'Investment Calculator',
      'Project investment value from contributions and an estimated return.',
      'ChartNoAxesCombined',
      ['investment', 'return', 'future value', 'growth'],
    ],
    [
      'car-loan-calculator',
      'Car Loan Calculator',
      'Estimate vehicle financing after down payment, trade-in, and fees.',
      'Car',
      ['car loan', 'auto loan', 'vehicle finance'],
    ],
    [
      'amortization-calculator',
      'Amortization Calculator',
      'Calculate a payment and inspect its principal and interest schedule.',
      'TableProperties',
      ['amortization', 'loan schedule', 'principal interest'],
    ],
    [
      'calorie-calculator',
      'Calorie Calculator',
      'Estimate adult BMR and daily maintenance calories.',
      'Flame',
      ['calories', 'bmr', 'tdee', 'maintenance calories'],
    ],
  ].map(([id, name, description, icon, keywords]) => ({
    id: id as string,
    name: name as string,
    slug: `calculator/${id}`,
    description: description as string,
    category: 'calculator' as const,
    icon: icon as string,
    keywords: keywords as string[],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser' as const,
    faq: commonFaq(name as string, true),
  })),
  ...[
    [
      'discount-calculator',
      'Discount Calculator',
      'Find sale price, discount amount, and percentage saved.',
      'Tags',
      ['discount', 'sale price', 'percentage off'],
    ],
    [
      'profit-margin-calculator',
      'Profit Margin Calculator',
      'Calculate profit, gross margin, and markup from cost and revenue.',
      'ChartPie',
      ['margin calculator', 'gross margin', 'profit percentage'],
    ],
    [
      'markup-calculator',
      'Markup Calculator',
      'Convert a cost and markup percentage into a selling price and margin.',
      'BadgePercent',
      ['markup', 'selling price', 'margin'],
    ],
    [
      'savings-calculator',
      'Savings Calculator',
      'Project savings from a starting balance, monthly deposits, and interest.',
      'PiggyBank',
      ['savings growth', 'monthly savings', 'interest'],
    ],
    [
      'savings-goal-calculator',
      'Savings Goal Calculator',
      'Estimate a monthly contribution or time needed to reach a savings goal.',
      'Goal',
      ['savings goal', 'monthly deposit', 'time to save'],
    ],
    [
      'retirement-calculator',
      'Retirement Calculator',
      'Project retirement savings without jurisdiction-specific pension assumptions.',
      'Sunset',
      ['retirement savings', 'retirement target', 'future value'],
    ],
    [
      'debt-payoff-calculator',
      'Debt Payoff Calculator',
      'Estimate payoff time, interest, and savings from extra payments.',
      'CircleDollarSign',
      ['debt payoff', 'pay off debt', 'extra payment'],
    ],
    [
      'credit-card-payoff-calculator',
      'Credit Card Payoff Calculator',
      'Estimate how long a card balance may take to repay.',
      'CreditCard',
      ['credit card payoff', 'APR', 'card balance'],
    ],
    [
      'fuel-cost-calculator',
      'Fuel Cost Calculator',
      'Estimate fuel required and trip cost in metric or imperial units.',
      'Fuel',
      ['fuel cost', 'gas calculator', 'petrol cost', 'trip cost'],
    ],
    [
      'pace-calculator',
      'Pace Calculator',
      'Calculate running pace and speed from distance and elapsed time.',
      'Timer',
      ['running pace', 'mile pace', 'km pace', '5k pace'],
    ],
    [
      'body-fat-calculator',
      'Body Fat Calculator',
      'Estimate body fat percentage using the U.S. Navy circumference method.',
      'ScanLine',
      ['body fat', 'navy method', 'body composition'],
    ],
    [
      'ideal-weight-calculator',
      'Ideal Weight Calculator',
      'Compare four recognized height-based reference-weight formulas.',
      'Scale',
      ['ideal weight', 'Devine formula', 'healthy weight'],
    ],
    [
      'water-intake-calculator',
      'Water Intake Calculator',
      'Estimate daily water intake from body weight and activity.',
      'GlassWater',
      ['water intake', 'hydration', 'daily water'],
    ],
    [
      'due-date-calculator',
      'Due Date Calculator',
      'Estimate a pregnancy due date from LMP or conception date.',
      'Baby',
      ['due date', 'pregnancy due date', 'conception date'],
    ],
    [
      'pregnancy-calculator',
      'Pregnancy Calculator',
      'Estimate gestational age, due date, and trimester.',
      'CalendarHeart',
      ['pregnancy week', 'gestational age', 'due date'],
    ],
    [
      'square-footage-calculator',
      'Square Footage Calculator',
      'Calculate room or rectangular area in square feet and meters.',
      'Ruler',
      ['sq ft calculator', 'room area calculator', 'square meters'],
    ],
    [
      'concrete-calculator',
      'Concrete Calculator',
      'Estimate rectangular slab volume with an optional waste allowance.',
      'Cuboid',
      ['concrete volume', 'cement calculator', 'cubic yards'],
    ],
    [
      'paint-calculator',
      'Paint Calculator',
      'Estimate paintable wall area and paint required for multiple coats.',
      'PaintBucket',
      ['paint coverage', 'wall paint', 'liters of paint'],
    ],
    [
      'fraction-calculator',
      'Fraction Calculator',
      'Add, subtract, multiply, divide, and simplify fractions.',
      'Divide',
      ['fraction math', 'simplify fraction', 'mixed number'],
    ],
    [
      'average-calculator',
      'Average Calculator',
      'Find count, sum, mean, median, minimum, and maximum.',
      'Sigma',
      ['average', 'mean', 'median', 'number list'],
    ],
  ].map(([id, name, description, icon, keywords]) => ({
    id: id as string,
    name: name as string,
    slug: `calculator/${id}`,
    description: description as string,
    category: 'calculator' as const,
    icon: icon as string,
    keywords: keywords as string[],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser' as const,
    faq: commonFaq(name as string, true),
  })),
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    description: 'Reduce PDF file size with clear quality controls.',
    category: 'pdf',
    icon: 'FileArchive',
    keywords: ['pdf', 'compress', 'reduce', 'size'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'planned',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Compress PDF'),
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    description: 'Arrange and combine PDF files into one document.',
    category: 'pdf',
    icon: 'Files',
    keywords: ['pdf', 'merge', 'combine', 'join'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Merge PDF', true),
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    description: 'Turn JPG images into an ordered PDF document.',
    category: 'pdf',
    icon: 'FileImage',
    keywords: ['jpg', 'jpeg', 'image', 'pdf', 'convert'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png',
    faq: commonFaq('JPG to PDF', true),
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    slug: 'compress-image',
    description: 'Make images lighter for sharing and the web.',
    category: 'image',
    icon: 'Minimize2',
    keywords: ['image', 'jpg', 'png', 'compress', 'optimize'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/*',
    faq: commonFaq('Compress Image', true),
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Extract selected pages or split every page into its own PDF.',
    category: 'pdf',
    icon: 'Scissors',
    keywords: ['pdf', 'split', 'extract', 'pages'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Split PDF', true),
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    slug: 'organize-pdf',
    description: 'Reorder, rotate, and remove PDF pages before export.',
    category: 'pdf',
    icon: 'PanelsTopLeft',
    keywords: ['pdf', 'organize', 'rotate', 'delete', 'reorder'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Organize PDF', true),
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    description: 'Render selected PDF pages as high-quality JPG images.',
    category: 'pdf',
    icon: 'Images',
    keywords: ['pdf', 'jpg', 'image', 'render', 'convert'],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('PDF to JPG', true),
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    slug: 'pdf-to-png',
    description: 'Render selected PDF pages as lossless PNG images.',
    category: 'pdf',
    icon: 'Images',
    keywords: ['pdf', 'png', 'image', 'render', 'convert'],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('PDF to PNG', true),
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    description: 'Rotate all or selected PDF pages by 90, 180, or 270 degrees.',
    category: 'pdf',
    icon: 'RotateCw',
    keywords: ['pdf', 'rotate', 'pages'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Rotate PDF', true),
  },
  {
    id: 'remove-pdf-pages',
    name: 'Remove PDF Pages',
    slug: 'remove-pdf-pages',
    description: 'Remove selected pages while keeping a valid PDF document.',
    category: 'pdf',
    icon: 'FileX2',
    keywords: ['pdf', 'remove', 'delete', 'pages'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Remove PDF Pages', true),
  },
  {
    id: 'extract-pdf-pages',
    name: 'Extract PDF Pages',
    slug: 'extract-pdf-pages',
    description: 'Create one new PDF from selected pages and ranges.',
    category: 'pdf',
    icon: 'FileOutput',
    keywords: ['pdf', 'extract', 'select', 'pages', 'range'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Extract PDF Pages', true),
  },
  {
    id: 'add-page-numbers-to-pdf',
    name: 'Add Page Numbers to PDF',
    slug: 'add-page-numbers-to-pdf',
    description: 'Add customizable page numbers to the footer of every PDF page.',
    category: 'pdf',
    icon: 'ListOrdered',
    keywords: ['pdf', 'page numbers', 'footer', 'number'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Add Page Numbers to PDF', true),
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    slug: 'resize-image',
    description: 'Resize images precisely while preserving aspect ratio.',
    category: 'image',
    icon: 'Scaling',
    keywords: ['image', 'photo', 'resize', 'dimensions', 'pixels'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png,image/webp',
    faq: commonFaq('Resize Image', true),
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    slug: 'jpg-to-png',
    description: 'Convert JPG images to PNG locally in your browser.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['jpg', 'jpeg', 'png', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg',
    faq: commonFaq('JPG to PNG', true),
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    slug: 'png-to-jpg',
    description: 'Convert PNG images to compact JPG with a chosen background.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['png', 'jpg', 'jpeg', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/png',
    faq: commonFaq('PNG to JPG', true),
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WebP',
    slug: 'jpg-to-webp',
    description: 'Convert JPG images to modern WebP format.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['jpg', 'jpeg', 'webp', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg',
    faq: commonFaq('JPG to WebP', true),
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    slug: 'webp-to-jpg',
    description: 'Convert WebP images to widely compatible JPG.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['webp', 'jpg', 'jpeg', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/webp',
    faq: commonFaq('WebP to JPG', true),
  },
  {
    id: 'image-to-text',
    name: 'Image to Text',
    slug: 'image-to-text',
    description: 'Extract readable text from screenshots and photos.',
    category: 'image',
    icon: 'ScanText',
    keywords: ['image', 'ocr', 'text', 'extract'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png,image/webp',
    faq: commonFaq('Image to Text', true),
  },
  {
    id: 'media-info',
    name: 'Media Info',
    slug: 'media-info',
    description: 'Inspect video and audio metadata locally without uploading your file.',
    category: 'video',
    icon: 'Info',
    keywords: ['media', 'metadata', 'codec', 'duration', 'video', 'audio'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept:
      'video/mp4,video/quicktime,video/webm,audio/mp4,audio/mpeg,audio/ogg,audio/wav,audio/webm,audio/flac,audio/aac',
    faq: commonFaq('Media Info', true),
  },
  {
    id: 'mp4-to-mp3',
    name: 'MP4 to MP3',
    slug: 'mp4-to-mp3',
    description: 'Extract an audio track from an MP4 video.',
    category: 'video',
    icon: 'FileAudio',
    keywords: ['mp4', 'mp3', 'video', 'audio', 'convert'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'planned',
    accept: 'video/mp4',
    faq: commonFaq('MP4 to MP3'),
  },
  {
    id: 'qr-generator',
    name: 'QR Generator',
    slug: 'qr-generator',
    description: 'Create a downloadable QR code for a link or text.',
    category: 'business',
    icon: 'QrCode',
    keywords: ['qr', 'code', 'link', 'generator'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('QR Generator', true),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    description: 'Format, validate, and minify JSON in your browser.',
    category: 'developer',
    icon: 'Braces',
    keywords: ['json', 'format', 'validate', 'minify', 'developer'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('JSON Formatter', true),
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    slug: 'remove-background',
    description: 'Prepare clean cut-outs from product and portrait images.',
    category: 'image',
    icon: 'Layers',
    keywords: ['image', 'background', 'remove', 'transparent'],
    featured: true,
    requiresAuth: false,
    premium: true,
    engine: 'planned',
    accept: 'image/*',
    faq: commonFaq('Remove Background'),
  },
  {
    id: 'ai-image-generator',
    name: 'AI Image Generator',
    slug: 'ai-image-generator',
    description: 'Create original visuals from a written brief.',
    category: 'ai',
    icon: 'WandSparkles',
    keywords: ['ai', 'image', 'generate', 'creative'],
    featured: true,
    requiresAuth: true,
    premium: true,
    engine: 'planned',
    faq: commonFaq('AI Image Generator'),
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    slug: 'base64-encoder',
    description: 'Encode Unicode text as Base64 locally.',
    category: 'developer',
    icon: 'Binary',
    keywords: ['base64', 'encode', 'unicode'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Base64 Encoder', true),
  },
  {
    id: 'base64-decoder',
    name: 'Base64 Decoder',
    slug: 'base64-decoder',
    description: 'Decode Base64 into readable Unicode text.',
    category: 'developer',
    icon: 'Binary',
    keywords: ['base64', 'decode', 'unicode'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Base64 Decoder', true),
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    slug: 'url-encoder',
    description: 'Safely encode text for use in URL components.',
    category: 'developer',
    icon: 'Link',
    keywords: ['url', 'percent', 'encode', 'uri'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('URL Encoder', true),
  },
  {
    id: 'url-decoder',
    name: 'URL Decoder',
    slug: 'url-decoder',
    description: 'Decode percent-encoded URL components.',
    category: 'developer',
    icon: 'Unlink',
    keywords: ['url', 'percent', 'decode', 'uri'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('URL Decoder', true),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    description: 'Inspect JWT headers and payloads without claiming validity.',
    category: 'developer',
    icon: 'KeyRound',
    keywords: ['jwt', 'token', 'header', 'payload', 'decode'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('JWT Decoder', true),
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    description: 'Generate SHA-256, SHA-384 or SHA-512 hashes with Web Crypto.',
    category: 'developer',
    icon: 'Hash',
    keywords: ['hash', 'sha256', 'sha512', 'checksum'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Hash Generator', true),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    slug: 'timestamp-converter',
    description: 'Convert Unix seconds or milliseconds into UTC and local dates.',
    category: 'developer',
    icon: 'Clock',
    keywords: ['unix', 'timestamp', 'epoch', 'date', 'time'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Timestamp Converter', true),
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    slug: 'word-counter',
    description: 'Count words, sentences, paragraphs and reading time.',
    category: 'developer',
    icon: 'Text',
    keywords: ['word count', 'writing', 'reading time', 'text'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Word Counter', true),
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    slug: 'character-counter',
    description: 'Count characters and characters without spaces.',
    category: 'developer',
    icon: 'CaseSensitive',
    keywords: ['character count', 'letters', 'length', 'text'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Character Counter', true),
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    slug: 'text-case-converter',
    description: 'Convert text between common writing and developer case styles.',
    category: 'developer',
    icon: 'CaseUpper',
    keywords: ['case', 'uppercase', 'lowercase', 'camel', 'snake', 'kebab'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Text Case Converter', true),
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    slug: 'json-validator',
    description: 'Validate, format and inspect JSON locally.',
    category: 'developer',
    icon: 'FileJson',
    keywords: ['json', 'validate', 'format', 'minify'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('JSON Validator', true),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    slug: 'password-generator',
    description: 'Create passwords using cryptographically secure browser randomness.',
    category: 'business',
    icon: 'ShieldCheck',
    keywords: ['password', 'secure', 'random', 'generator'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Password Generator', true),
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    slug: 'csv-to-json',
    description: 'Convert standards-compliant CSV into structured JSON locally.',
    category: 'developer',
    icon: 'Table2',
    keywords: ['csv json', 'csv converter', 'spreadsheet', 'data'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.csv,text/csv',
    faq: commonFaq('CSV to JSON', true),
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    slug: 'json-to-csv',
    description: 'Convert an array of flat JSON objects into correctly escaped CSV.',
    category: 'developer',
    icon: 'FileSpreadsheet',
    keywords: ['json csv', 'csv converter', 'export', 'data'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.json,application/json',
    faq: commonFaq('JSON to CSV', true),
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    slug: 'invoice-generator',
    description: 'Create a professional browser-local invoice and downloadable PDF.',
    category: 'business',
    icon: 'ReceiptText',
    keywords: ['invoice maker', 'free invoice generator', 'invoice pdf', 'billing'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/png,image/jpeg',
    faq: commonFaq('Invoice Generator', true),
  },
  {
    id: 'quotation-generator',
    name: 'Quotation Generator',
    slug: 'quotation-generator',
    description: 'Create a professional quotation PDF without storing customer data.',
    category: 'business',
    icon: 'FileSignature',
    keywords: ['quotation maker', 'quote generator', 'estimate pdf'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/png,image/jpeg',
    faq: commonFaq('Quotation Generator', true),
  },
  {
    id: 'signature-generator',
    name: 'Signature Generator',
    slug: 'signature-generator',
    description: 'Type or draw a transparent signature image locally.',
    category: 'business',
    icon: 'PenTool',
    keywords: ['signature maker', 'draw signature', 'signature png'],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('Signature Generator', true),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    description: 'Generate unique identifiers for apps and test data.',
    category: 'developer',
    icon: 'Fingerprint',
    keywords: ['uuid', 'guid', 'developer', 'generate'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('UUID Generator', true),
  },
];

export const toolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
export const categoryBySlug = (slug: string) => categories.find((category) => category.id === slug);
export const toolsForCategory = (category: ToolCategory) => tools.filter((tool) => tool.category === category);
export const searchTools = (query: string) => {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return tools;
  }

  const tokens = normalized.split(/\s+/u);

  return tools
    .filter((tool) => tool.engine === 'browser')
    .map((tool) => {
      const name = tool.name.toLowerCase();
      const keywords = tool.keywords.join(' ').toLowerCase();
      const searchable = `${name} ${tool.description} ${tool.category} ${keywords}`.toLowerCase();
      const score =
        (name === normalized ? 100 : name.includes(normalized) ? 50 : 0) +
        tokens.reduce((total, token) => total + (name.includes(token) ? 10 : keywords.includes(token) ? 5 : 1), 0);

      return { tool, searchable, score };
    })
    .filter(({ searchable }) => tokens.every((token) => searchable.includes(token)))
    .sort((a, b) => b.score - a.score)
    .map(({ tool }) => tool);
};
