import type { CategoryDefinition, ToolCategory, ToolDefinition } from './types';

export const categories: CategoryDefinition[] = [
  { id: 'pdf', name: 'PDF', description: 'Organize, convert, and prepare documents.', icon: 'FileText' },
  { id: 'image', name: 'Images', description: 'Resize, convert, extract, and enhance images.', icon: 'Image' },
  { id: 'video', name: 'Video', description: 'Convert and optimize video for any destination.', icon: 'Clapperboard' },
  { id: 'audio', name: 'Audio', description: 'Convert, trim, and prepare sound files.', icon: 'AudioLines' },
  {
    id: 'business',
    name: 'Business',
    description: 'Create practical assets for daily work.',
    icon: 'BriefcaseBusiness',
  },
  { id: 'developer', name: 'Developer', description: 'Inspect, format, and generate developer data.', icon: 'Braces' },
  { id: 'ai', name: 'AI', description: 'Focused assistants for creative and knowledge work.', icon: 'Sparkles' },
  {
    id: 'web',
    name: 'Web / Development',
    description: 'Build, test, and ship better web experiences.',
    icon: 'CodeXml',
  },
];

const commonFaq = (name: string, browser = false) => [
  {
    question: `How does ${name} work?`,
    answer: browser
      ? 'This tool runs in your browser. Follow the workspace prompts to complete the task.'
      : 'The interface is ready, but the processing engine is not connected yet. No output is fabricated.',
  },
  {
    question: 'Do I need an account?',
    answer: 'No account is required for the basic browser tools currently available.',
  },
  {
    question: 'What happens to my files?',
    answer: browser
      ? 'Files used by this tool stay in your browser for the current session.'
      : 'Files are not uploaded or processed while this preview engine is unavailable.',
  },
];

export const tools: ToolDefinition[] = [
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    description: 'Reduce PDF file size with clear quality controls.',
    category: 'pdf',
    icon: 'FileArchive',
    keywords: ['pdf', 'compress', 'reduce', 'size'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'planned',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Compress PDF'),
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    description: 'Arrange and combine PDF files into one document.',
    category: 'pdf',
    icon: 'Files',
    keywords: ['pdf', 'merge', 'combine', 'join'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Merge PDF', true),
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    description: 'Turn JPG images into an ordered PDF document.',
    category: 'pdf',
    icon: 'FileImage',
    keywords: ['jpg', 'jpeg', 'image', 'pdf', 'convert'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png',
    faq: commonFaq('JPG to PDF', true),
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    slug: 'compress-image',
    description: 'Make images lighter for sharing and the web.',
    category: 'image',
    icon: 'Minimize2',
    keywords: ['image', 'jpg', 'png', 'compress', 'optimize'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/*',
    faq: commonFaq('Compress Image', true),
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Extract selected pages or split every page into its own PDF.',
    category: 'pdf',
    icon: 'Scissors',
    keywords: ['pdf', 'split', 'extract', 'pages'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Split PDF', true),
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    slug: 'organize-pdf',
    description: 'Reorder, rotate, and remove PDF pages before export.',
    category: 'pdf',
    icon: 'PanelsTopLeft',
    keywords: ['pdf', 'organize', 'rotate', 'delete', 'reorder'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Organize PDF', true),
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    description: 'Render selected PDF pages as high-quality JPG images.',
    category: 'pdf',
    icon: 'Images',
    keywords: ['pdf', 'jpg', 'image', 'render', 'convert'],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('PDF to JPG', true),
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    slug: 'pdf-to-png',
    description: 'Render selected PDF pages as lossless PNG images.',
    category: 'pdf',
    icon: 'Images',
    keywords: ['pdf', 'png', 'image', 'render', 'convert'],
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('PDF to PNG', true),
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    description: 'Rotate all or selected PDF pages by 90, 180, or 270 degrees.',
    category: 'pdf',
    icon: 'RotateCw',
    keywords: ['pdf', 'rotate', 'pages'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Rotate PDF', true),
  },
  {
    id: 'remove-pdf-pages',
    name: 'Remove PDF Pages',
    slug: 'remove-pdf-pages',
    description: 'Remove selected pages while keeping a valid PDF document.',
    category: 'pdf',
    icon: 'FileX2',
    keywords: ['pdf', 'remove', 'delete', 'pages'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Remove PDF Pages', true),
  },
  {
    id: 'extract-pdf-pages',
    name: 'Extract PDF Pages',
    slug: 'extract-pdf-pages',
    description: 'Create one new PDF from selected pages and ranges.',
    category: 'pdf',
    icon: 'FileOutput',
    keywords: ['pdf', 'extract', 'select', 'pages', 'range'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Extract PDF Pages', true),
  },
  {
    id: 'add-page-numbers-to-pdf',
    name: 'Add Page Numbers to PDF',
    slug: 'add-page-numbers-to-pdf',
    description: 'Add customizable page numbers to the footer of every PDF page.',
    category: 'pdf',
    icon: 'ListOrdered',
    keywords: ['pdf', 'page numbers', 'footer', 'number'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: '.pdf,application/pdf',
    faq: commonFaq('Add Page Numbers to PDF', true),
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    slug: 'resize-image',
    description: 'Resize images precisely while preserving aspect ratio.',
    category: 'image',
    icon: 'Scaling',
    keywords: ['image', 'resize', 'dimensions', 'pixels'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png,image/webp',
    faq: commonFaq('Resize Image', true),
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    slug: 'jpg-to-png',
    description: 'Convert JPG images to PNG locally in your browser.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['jpg', 'jpeg', 'png', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg',
    faq: commonFaq('JPG to PNG', true),
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    slug: 'png-to-jpg',
    description: 'Convert PNG images to compact JPG with a chosen background.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['png', 'jpg', 'jpeg', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/png',
    faq: commonFaq('PNG to JPG', true),
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WebP',
    slug: 'jpg-to-webp',
    description: 'Convert JPG images to modern WebP format.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['jpg', 'jpeg', 'webp', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg',
    faq: commonFaq('JPG to WebP', true),
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    slug: 'webp-to-jpg',
    description: 'Convert WebP images to widely compatible JPG.',
    category: 'image',
    icon: 'RefreshCw',
    keywords: ['webp', 'jpg', 'jpeg', 'convert'],
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/webp',
    faq: commonFaq('WebP to JPG', true),
  },
  {
    id: 'image-to-text',
    name: 'Image to Text',
    slug: 'image-to-text',
    description: 'Extract readable text from screenshots and photos.',
    category: 'image',
    icon: 'ScanText',
    keywords: ['image', 'ocr', 'text', 'extract'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept: 'image/jpeg,image/png,image/webp',
    faq: commonFaq('Image to Text', true),
  },
  {
    id: 'media-info',
    name: 'Media Info',
    slug: 'media-info',
    description: 'Inspect video and audio metadata locally without uploading your file.',
    category: 'video',
    icon: 'Info',
    keywords: ['media', 'metadata', 'codec', 'duration', 'video', 'audio'],
    featured: true,
    new: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    accept:
      'video/mp4,video/quicktime,video/webm,audio/mp4,audio/mpeg,audio/ogg,audio/wav,audio/webm,audio/flac,audio/aac',
    faq: commonFaq('Media Info', true),
  },
  {
    id: 'mp4-to-mp3',
    name: 'MP4 to MP3',
    slug: 'mp4-to-mp3',
    description: 'Extract an audio track from an MP4 video.',
    category: 'video',
    icon: 'FileAudio',
    keywords: ['mp4', 'mp3', 'video', 'audio', 'convert'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'planned',
    accept: 'video/mp4',
    faq: commonFaq('MP4 to MP3'),
  },
  {
    id: 'qr-generator',
    name: 'QR Generator',
    slug: 'qr-generator',
    description: 'Create a downloadable QR code for a link or text.',
    category: 'business',
    icon: 'QrCode',
    keywords: ['qr', 'code', 'link', 'generator'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('QR Generator', true),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    description: 'Format, validate, and minify JSON in your browser.',
    category: 'developer',
    icon: 'Braces',
    keywords: ['json', 'format', 'validate', 'minify', 'developer'],
    featured: true,
    requiresAuth: false,
    premium: false,
    engine: 'browser',
    faq: commonFaq('JSON Formatter', true),
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    slug: 'remove-background',
    description: 'Prepare clean cut-outs from product and portrait images.',
    category: 'image',
    icon: 'Layers',
    keywords: ['image', 'background', 'remove', 'transparent'],
    featured: true,
    requiresAuth: false,
    premium: true,
    engine: 'planned',
    accept: 'image/*',
    faq: commonFaq('Remove Background'),
  },
  {
    id: 'ai-image-generator',
    name: 'AI Image Generator',
    slug: 'ai-image-generator',
    description: 'Create original visuals from a written brief.',
    category: 'ai',
    icon: 'WandSparkles',
    keywords: ['ai', 'image', 'generate', 'creative'],
    featured: true,
    requiresAuth: true,
    premium: true,
    engine: 'planned',
    faq: commonFaq('AI Image Generator'),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    description: 'Generate unique identifiers for apps and test data.',
    category: 'developer',
    icon: 'Fingerprint',
    keywords: ['uuid', 'guid', 'developer', 'generate'],
    requiresAuth: false,
    premium: false,
    engine: 'planned',
    faq: commonFaq('UUID Generator'),
  },
];

export const toolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
export const categoryBySlug = (slug: string) => categories.find((category) => category.id === slug);
export const toolsForCategory = (category: ToolCategory) => tools.filter((tool) => tool.category === category);
export const searchTools = (query: string) => {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return tools;
  }

  return tools.filter((tool) =>
    [tool.name, tool.description, tool.category, ...tool.keywords].join(' ').toLowerCase().includes(normalized),
  );
};
