services:
  app-prod:
    image: freebee-tools:production
    build:
      context: .
      dockerfile: Dockerfile
      target: freebee-tools-production
      args:
        VITE_PUBLIC_SITE_URL: ${VITE_PUBLIC_SITE_URL:-http://localhost:5173}
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
    profiles: [production]

  app-dev:
    image: freebee-tools:development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: pnpm run dev --host 0.0.0.0
    profiles: [development, default]
