name: Setup and Build
description: Generic setup action
inputs:
  pnpm-version:
    required: false
    type: string
    default: '9.14.4'
  node-version:
    required: false
    type: string
    default: '22.22.0'

runs:
  using: composite

  steps:
    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Activate pnpm ${{ inputs.pnpm-version }} with Corepack
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@${{ inputs.pnpm-version }} --activate
        pnpm --version

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
